<?php
/**
 * MB-it Gitosis Web Configuration
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  - Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 *  - Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 *  - Neither the name MB-it nor the names of its contributors may be used to
 *    endorse or promote products derived from this software without specific
 *    prior written permission.
 *
 * @copyright Copyright (c) 2011-2020 MB-it (http://www.mb-it.com)
 * @author    Marc Becker <m.becker@mb-it.com>
 * @category  MB-it
 * @package   View
 */
?>
<?php echo  $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <base href="<?php echo $this->baseUrl(); ?>"/>
    <meta http-equiv="content-type" content="text/html; charset=<?php echo $this->getEncoding() ?>"/>

    <?php echo $this->headTitle() ?>


    <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/themes/mb-it/styles/style.css')) ?>

</head>
<body>
    <div id="page">

        <div id="header">
            <?php echo $this->partial('accountLink.phtml'); ?>

            <div id="title">Gitosis Web Configuration</div>

            <div id="logo">
                <a href="http://www.mb-it.com"><img src="<?php echo $this->baseUrl('/themes/mb-it/images/logo.jpg'); ?>" alt="MB-it" width="200" /></a>
            </div>

            <div id="mainnav">
                &nbsp;
            </div>

            <div id="subnav">
                &nbsp;
            </div>
        </div>

        <div id="main">

            <div id="content">
                <?php echo $this->layout()->content; ?>
            </div>

        <p><br class="clearboth" /></p>
        </div>

        <div id="footer">
            <span id="copyright">Gitosis Web Configuration</span>
            <span id="metanav">
                <a href="http://www.mb-it.com" target="_blank">MB-it</a> | <a href="https://github.com/mb-it/gitosis-web-configuration" target="_blank">github</a> | <a href="<?php echo $this->url(array('controller' => 'license'), null, true); ?>">Lizenz</a></span>
        </div>
    </div>
</body>
</html>
