<?php
/**
 * MB-it Gitosis Web Configuration
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  - Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 *  - Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 *  - Neither the name MB-it nor the names of its contributors may be used to
 *    endorse or promote products derived from this software without specific
 *    prior written permission.
 *
 * @copyright Copyright (c) 2011-2020 MB-it (http://www.mb-it.com)
 * @author    Marc Becker <m.becker@mb-it.com>
 * @category  MB-it
 * @package   View
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <base href="<?php echo $this->baseUrl(); ?>"/>

    <meta http-equiv="content-type" content="text/html; charset=<?php echo $this->getEncoding() ?>"/>
    <?php echo $this->headTitle(); ?>

    <?php echo $this->headScript()
                    ->offsetSetFile(-100,$this->baseUrl('/scripts/jquery-1.5.2.min.js'))
                    ->offsetSetFile(-99,$this->baseUrl('/scripts/superfish.js'))
                    ->offsetSetFile(-50,$this->baseUrl('/scripts/init.js')); ?>

    <?php echo $this->headLink()
                    ->appendStylesheet($this->baseUrl('/css/yaml/core/base.css'))
                    ->appendStylesheet($this->baseUrl('/css/basemod.css'))
                    ->appendStylesheet($this->baseUrl('/css/yaml/core/iehacks.css'))
                    ->appendStylesheet($this->baseUrl('/css/layout.css'))
                    ->appendStylesheet($this->baseUrl('/css/superfish.css'))
                    ->appendStylesheet($this->baseUrl('/css/patches.css'), 'all', 'lte IE 7'); ?>
</head>
<body>
    <div class="page_margins">
        <div class="page">
            <div id="header">
                <div id="topnav">
                    <a class="skip" title="skip link" href="#navigation">Skip to the navigation</a>
                    <span class="hideme">.</span>
                    <a class="skip" title="skip link" href="#content">Skip to the content</a>
                    <span class="hideme">.</span>
                </div>
            </div>
            <div id="nav">

                <a id="navigation" name="navigation"></a>
                <div class="hlist">
                    <?php echo $this->navigation()->menu()
                                                  ->setUlClass('sf-menu sf-js-enabled sf-shadow'); ?>
                </div>
            </div>
            <div id="main">
                <?php echo $this->layout()->content ?>
            </div>
            <div id="footer">
                &copy; <a href="http://www.mb-it.com" target="_blank">MB-it</a>, 2011-2020
            </a>
            </div>
        </div>
    </div>
</body>
</html>
