<?php
/**
 * MB-it Gitosis Web Configuration
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  - Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 *  - Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 *  - Neither the name MB-it nor the names of its contributors may be used to
 *    endorse or promote products derived from this software without specific
 *    prior written permission.
 *
 * @copyright Copyright (c) 2011-2020 MB-it (http://www.mb-it.com)
 * @author    Marc Becker <m.becker@mb-it.com>
 * @category  MB-it
 * @package   View
 */
?>
<?php $this->headScript()->captureStart(); ?>
jQuery('document').ready(function (){
    jQuery('input[type=checkbox]').bind(
        'click',
        function () {
            var baseHref = jQuery('base').attr('href');

            var attribId = jQuery(this).attr('id');
            var userId   = attribId.replace('gitosis_user_id_', '');
            var groupId  = jQuery('#gitosis_group_id').val();

            var isChecked = jQuery(this).is(':checked');
            var action    = 'unknown';

            if (isChecked) {
                action = 'add';
            } else {
                action = 'remove';
            }

            jQuery('#main table').fadeTo('fast', 0.2);
            jQuery('#ajaxLoader').toggle();

            jQuery.post(
                baseHref + '/group/ajax/format/json',
                {
                    operation: action,
                    userId:    userId,
                    groupId:   groupId
                },
                function (data) {
                    jQuery('#ajaxLoader').toggle();
                    jQuery('#main table').fadeTo('fast', 1);

                    jQuery('#messages ul').empty();
                    jQuery('#messages ul').html('<li>' + data.message + '</li>');
                    jQuery('#messages').show();

                    setTimeout(
                        function() {
                            jQuery("#messages").fadeOut('slow');
                        },
                        5000
                    );
                },
                'json'
            );
        }
    );
});
<?php $this->headScript()->captureEnd(); ?>

<?php echo $this->partial('ajaxLoader.phtml'); ?>

<div id="toolbar">
    <?php echo $this->partial('backButton.phtml'); ?>
</div>

<h1>Gitosis Gruppe &quot<?php echo $this->escape($this->group) ?>&quot; verwalten</h1>
<?php echo $this->formHidden('gitosis_group_id', $this->groupId); ?>

<div id="messages" style="display: none;">
    <ul>
    </ul>
</div>

<?php if ($this->pager->count() < 1): ?>
    keine Benutzer im System erfasst
<?php else: ?>
    <table width="100%">
        <thead>
            <tr>
                <th width="40%">Name</th>
                <th width="40%">E-Mail</th>
                <th width="20%" class="center">in Gruppe enthalten</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->pager as $row): ?>
            <tr style="background-color:<?php echo $this->cycle(array("#FFFFFF",
                                                                      "#F0F0F0"))
                                                        ->next(); ?>">
                <td><?php echo $this->escape($row->{'gitosis_user_name'}); ?></td>
                <td><?php echo $this->escape($row->{'gitosis_user_email'}); ?></td>
                <td class="center">
                    <?php if ($this->user()->isInGroup($this->groupId, $row->{'gitosis_user_id'})): ?>
                        <?php $attribs['checked'] = true; ?>
                    <?php else: ?>
                        <?php $attribs = null; ?>
                    <?php endif; ?>
                    <?php echo $this->formCheckbox('gitosis_user_id_' . $row->{'gitosis_user_id'}, null, $attribs); ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php echo $this->pager; ?>
<?php endif; ?>