<?php
/**
 * MB-it Gitosis Web Configuration
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  - Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 *  - Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 *  - Neither the name MB-it nor the names of its contributors may be used to
 *    endorse or promote products derived from this software without specific
 *    prior written permission.
 *
 * @copyright Copyright (c) 2011-2020 MB-it (http://www.mb-it.com)
 * @author    Marc Becker <m.becker@mb-it.com>
 * @category  MB-it
 * @package   View
 */
?>
<div id="toolbar">
    <a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'create'), null, true) ?>">
        <img src="<?php echo $this->theme()->getUrl('/images/icons/group_add.png') ?>" alt="Gruppe erstellen" title="Gruppe erstellen" />
        neue Gruppe erstellen
    </a>
</div>

<h1>Gitosis Gruppen</h1>

<?php echo $this->partial('messages.phtml', array('messages' => $this->messages)); ?>

<?php if ($this->pager->count() < 1): ?>
    keine Gruppen im System erfasst
<?php else: ?>
    <table width="100%">
        <thead>
            <tr>
                <th width="80%">Name</th>
                <th width="20%">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->pager as $group): ?>
            <tr style="background-color:<?php echo $this->cycle(array("#FFFFFF",
                                                                      "#F0F0F0"))
                                                        ->next(); ?>">
                <td><?php echo $this->escape($group->getName()); ?></td>
                <td class="center">
                    <?php if ($group->getName() !== 'gitosis-admin') :?>
                        <a href="<?php echo $this->url(array('action' => 'edit', 'controller' => 'group', 'id' => $group->getId()), null, true); ?>">
                            <img src="<?php echo $this->theme()->getUrl('/images/icons/group_edit.png'); ?>" alt="Bearbeiten" title="Bearbeiten" />
                        </a>
                        <a href="<?php echo $this->url(array('action' => 'delete', 'controller' => 'group', 'id' => $group->getId()), null, true); ?>">
                            <img src="<?php echo $this->theme()->getUrl('/images/icons/group_delete.png'); ?>" alt="Löschen" title="Löschen" />
                        </a>
                    <? endif; ?>
                    <a href="<?php echo $this->url(array('action' => 'user', 'controller' => 'group', 'id' => $group->getId()), null, true); ?>">
                        <img src="<?php echo $this->theme()->getUrl('/images/icons/user_groups.png'); ?>" alt="Benutzer verwalten" title="Benutzer verwalten" />
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php echo $this->pager; ?>
<?php endif; ?>