<?php
/**
 * MB-it Gitosis Web Configuration
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  - Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 *  - Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 *  - Neither the name MB-it nor the names of its contributors may be used to
 *    endorse or promote products derived from this software without specific
 *    prior written permission.
 *
 * @copyright Copyright (c) 2011-2020 MB-it (http://www.mb-it.com)
 * @author    Marc Becker <m.becker@mb-it.com>
 * @category  MB-it
 * @package   View
 */
?>
<?php $this->headScript()->captureStart(); ?>
jQuery('document').ready(function (){
    jQuery('#submit').bind('click', function(){
        var email = jQuery('#email').val();
        if(email.length > 0) {

            var baseHref = jQuery('base').attr('href');
            jQuery.getJSON(
                baseHref + '/index/load-repositories/format/json',
                { email: email },
                function (data) {
                    jQuery('#repos ul').empty();
                    
                    var repositories = data.repositories;
                    jQuery.each(repositories, function (index, value) {
                        jQuery('#repos ul').append('<li>' + value.repo + '</li>');
                        jQuery('#repos').show();
                    });
                }
            );
        }
    });
});
<?php $this->headScript()->captureEnd(); ?>
<?php echo $this->partial('messages.phtml', array('messages' => $this->messages)); ?>

<?php echo $this->formLabel('email', 'E-Mail:'); ?>&nbsp;
<?php echo $this->formText('email'); ?>&nbsp;
<?php echo $this->formSubmit('submit', 'Repositories laden'); ?>

<div id="repos" style="display: none">
    <ul></ul>
</div>