<?php
/**
 * MB-it Gitosis Web Configuration
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  - Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 *  - Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 *  - Neither the name MB-it nor the names of its contributors may be used to
 *    endorse or promote products derived from this software without specific
 *    prior written permission.
 *
 * @copyright Copyright (c) 2011-2020 MB-it (http://www.mb-it.com)
 * @author    Marc Becker <m.becker@mb-it.com>
 * @category  MB-it
 * @package   View
 */
?>
<?php $this->headScript()->captureStart(); ?>
jQuery('document').ready(function (){
    jQuery('#submit').bind('click', function(){
        var email = jQuery('#email').val();
        if(email.length > 0) {

            var baseHref = jQuery('base').attr('href');
            jQuery.getJSON(
                baseHref + '/index/load-repositories/format/json',
                { email: email },
                function (data) {
                    jQuery('#repos ul').empty();

                    var repositories = data.repositories;
                    var liElement = '';
                    jQuery.each(repositories, function (index, value) {
                        liElement += '<li';
                        if (value.write == true) {
                            liElement += ' class="write">';
                        } else {
                            liElement += ' class="read">';
                        }
                        liElement += value.repo +
                                     '<ul class="subList">' +
                                        '<li><span class="title">URL:</span> ' + value.url + '</li>' +
                                        '<li><span class="title">Beschreibung:</span> ' + value.desc + '</li>' +
                                     '</ul>' +
                                  '</li>';

                    });
                    jQuery('#repos ul').append(liElement);
                    jQuery('#repos').show();
                }
            );
        }
    });
});
<?php $this->headScript()->captureEnd(); ?>
<?php echo $this->partial('messages.phtml', array('messages' => $this->messages)); ?>

<?php echo $this->formLabel('email', 'E-Mail:'); ?>&nbsp;
<?php echo $this->formText('email'); ?>&nbsp;
<?php echo $this->formSubmit('submit', 'Repositories laden'); ?>

<div id="repos" style="display: none">
    Die folgenden Repositories sind für dich freigeschaltet. Auf grau hinterlegte Repositories
    hast du lediglich lesenden Zugriff, auf grün hinterlegte  Repositories hast du schreibenden Zugriff.
    <ul></ul>
</div>