<?php
/**
 * MB-it Gitosis Web Configuration
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  - Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 *  - Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 *  - Neither the name MB-it nor the names of its contributors may be used to
 *    endorse or promote products derived from this software without specific
 *    prior written permission.
 *
 * @copyright Copyright (c) 2011-2020 MB-it (http://www.mb-it.com)
 * @author    Marc Becker <m.becker@mb-it.com>
 * @category  MB-it
 * @package   View
 */
?>
<div id="toolbar">
    <a href="<?php echo $this->url(array('controller' => 'repository', 'action' => 'create'), null, true) ?>">
        <img src="<?php echo $this->theme()->getUrl('/images/icons/repo_add.png') ?>" alt="Repository erstellen" title="Repository erstellen" />
        neues Repository erstellen
    </a>
</div>

<h1>Gitosis Repositories</h1>

<?php
    $messages = $this->messages;
    if (!empty($messages)):
?>
    <div id="messages">
        <ul>
            <?php foreach ($messages as $message): ?>
                <li><?php echo $this->escape($message); ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<?php if ($this->pager->count() < 1): ?>
    keine Repositories im System erfasst
<?php else: ?>
    <table width="100%">
        <thead>
            <tr>
                <th width="20%">Name</th>
                <th width="50%">Beschreibung</th>
                <th width="20%">Besitzer</th>
                <th width="10%">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->pager as $repo): ?>
            <tr style="background-color:<?php echo $this->cycle(array("#FFFFFF",
                                                                      "#F0F0F0"))
                                                        ->next(); ?>">
                <td><?php echo $this->escape($repo->getName()); ?></td>
                <td><?php echo $this->escape($repo->getDescription()); ?></td>
                <td>
                    <?php if ($repo->getOwner() == null): ?>
                        &nbsp;
                    <?php else: ?>
                        <?php echo $this->escape($repo->getOwner()->getName()); ?>
                    <?php endif; ?>
                </td>
                <td class="center">
                    <a href="<?php echo $this->url(array('action' => 'edit', 'controller' => 'repository', 'id' => $repo->getId()), null, true); ?>">
                        <img src="<?php echo $this->theme()->getUrl('/images/icons/repo_edit.png'); ?>" alt="Bearbeiten" title="Bearbeiten" />
                    </a>
                    <a href="<?php echo $this->url(array('action' => 'delete', 'controller' => 'repository', 'id' => $repo->getId()), null, true); ?>">
                        <img src="<?php echo $this->theme()->getUrl('/images/icons/repo_delete.png'); ?>" alt="Löschen" title="Löschen" />
                    </a>
                    <a href="<?php echo $this->url(array('action' => 'permission', 'controller' => 'repository', 'id' => $repo->getId()), null, true); ?>">
                        <img src="<?php echo $this->theme()->getUrl('/images/icons/rights.png'); ?>" alt="Berechtigungen" title="Berechtigungen" />
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php echo $this->pager; ?>
<?php endif; ?>